#!/bin/bash
# This script compiles and installs the teabag-ml package using maven3.
# usage:
# build-teabagml

/media/uraplutonium/Workstation/Applications/apache-maven-3.3.3/bin/mvn clean install -DskipTests=true &&
upn-tea
